scripts/generate_routing_topo_graph.sh: drop -alsologtostderr parameter
* -alsologtostderr is not available since glog was changed to be built without gflags support in:
  https://github.com/ApolloAuto/apollo/commit/0b03b66c838ba878a9df1c468b3ba824a2f29bc7
* fixes:
  [apollo@in-runtime-docker:/apollo]$ scripts/generate_routing_topo_graph.sh
  ERROR: unknown command line flag 'alsologtostderr'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>